Repository opea-project/GenAIComps, pull requests merged in 2024-08, with the labels that each got.

#452 align vllm-ray response format to tgi response format
  comps/llms/text-generation/vllm-ray/llm.py
Labels: r0.8

#425 Optional container build instructions
  .github/workflows/microservice-test.yml
  comps/__init__.py
  comps/agent/langchain/docker/Dockerfile
  comps/asr/Dockerfile
  comps/asr/whisper/Dockerfile
  comps/asr/whisper/Dockerfile_hpu
  comps/cores/mega/gateway.py
  comps/cores/mega/micro_service.py
  comps/cores/mega/orchestrator.py
  comps/cores/proto/docarray.py
  comps/dataprep/milvus/config.py
  comps/dataprep/redis/README.md
  comps/dataprep/redis/langchain/prepare_doc_redis.py
  comps/embeddings/langchain-mosec/README.md
  comps/lvms/Dockerfile_tgi
  comps/lvms/lvm_tgi.py
  comps/lvms/requirements.txt
  comps/reranks/langchain-mosec/README.md
  comps/tts/Dockerfile
  comps/tts/speecht5/Dockerfile
  comps/tts/speecht5/Dockerfile_hpu
  tests/test_dataprep_redis_langchain.sh
  tests/test_embeddings_langchain-mosec.sh
  tests/test_lvms_tgi_llava_next.sh
  tests/test_reranks_langchain-mosec.sh
Labels: r0.8

#457 Optional container build instructions
  comps/agent/langchain/docker/Dockerfile
  comps/asr/Dockerfile
  comps/asr/whisper/Dockerfile
  comps/tts/Dockerfile
  comps/tts/speecht5/Dockerfile
Labels: r0.8

#525 adding entrypoint.sh to faq-generation comp
  comps/llms/faq-generation/tgi/Dockerfile
  comps/llms/faq-generation/tgi/entrypoint.sh
  comps/llms/faq-generation/tgi/requirements-runtime.txt
  comps/llms/faq-generation/tgi/requirements.txt
Labels: r0.8, r0.9

#528 Using habana docker 1.16.1 everywhere
  .github/workflows/scripts/freeze_images.sh
  comps/llms/text-generation/native/docker/Dockerfile
  comps/llms/text-generation/vllm-ray/docker/Dockerfile.vllmray
  comps/llms/text-generation/vllm/docker/Dockerfile.hpu
Labels: r0.9

#526 Use Gaudi base images from Dockerhub
  .github/workflows/scripts/freeze_images.sh
  comps/asr/whisper/Dockerfile_hpu
  comps/llms/text-generation/native/docker/Dockerfile
  comps/llms/text-generation/vllm-ray/docker/Dockerfile.vllmray
  comps/llms/text-generation/vllm/docker/Dockerfile.hpu
  comps/lvms/llava/Dockerfile_hpu
  comps/tts/speecht5/Dockerfile_hpu
Labels: r0.8, r0.9

#338 Add toxicity detection microservice
  comps/guardrails/toxicity_detection/README.md
  comps/guardrails/toxicity_detection/docker/Dockerfile
  comps/guardrails/toxicity_detection/requirements.txt
  comps/guardrails/toxicity_detection/toxicity_detection.py
  tests/test_guardrails_toxicity_detection.sh
Labels: r0.9

#548 Remove redundant dependency from 'vllm-ray' comps
  comps/llms/text-generation/vllm-ray/requirements.txt
Labels: r0.9

#553 Fix typos and add definitions for toxicity detection microservice
  comps/guardrails/README.md
  comps/guardrails/toxicity_detection/README.md
Labels: r0.9
