Repository opea-project/GenAIComps, pull requests merged in 2025-04, with the labels that each got.

#1433 MultimodalQnA audio features completion
  comps/cores/proto/api_protocol.py
  comps/dataprep/src/README_multimodal.md
  comps/dataprep/src/integrations/redis_multimodal.py
  comps/dataprep/src/integrations/utils/multimodal.py
  tests/asr/test_asr_whisper.sh
  tests/asr/test_asr_whisper_on_intel_hpu.sh
  tests/dataprep/ingest_dataprep_text.pdf
  tests/dataprep/test_dataprep_redis_multimodal.sh
Labels: r1.3

#1317 VDMS langchain package update
  .github/workflows/pr-microservice-test.yml
  comps/dataprep/src/Dockerfile
  comps/dataprep/src/integrations/utils/store_embeddings.py
  comps/dataprep/src/integrations/vdms.py
  comps/dataprep/src/integrations/vdms_multimodal.py
  comps/dataprep/src/requirements.txt
  comps/retrievers/deployment/docker_compose/compose.yaml
  comps/retrievers/src/Dockerfile
  comps/retrievers/src/integrations/config.py
  comps/retrievers/src/integrations/vdms.py
  comps/retrievers/src/requirements.txt
  tests/dataprep/test_dataprep_vdms.sh
  tests/dataprep/test_dataprep_vdms_multimodal.sh
  tests/retrievers/test_retrievers_vdms.sh
Labels: A1

#1439 Data Ingestion and Retrieval with custom index_name
  comps/cores/proto/api_protocol.py
  comps/cores/proto/docarray.py
  comps/dataprep/src/integrations/redis.py
  comps/dataprep/src/opea_dataprep_loader.py
  comps/dataprep/src/opea_dataprep_microservice.py
  comps/retrievers/src/integrations/redis.py
  tests/dataprep/dataprep_utils.sh
  tests/dataprep/test_dataprep_redis.sh
Labels: r1.3

#1493 feature: OpeaStore Class
  comps/cores/common/storage.py
  comps/cores/storages/__init__.py
  comps/cores/storages/arangodb.py
  comps/cores/storages/developer.md
  comps/cores/storages/models.py
  requirements.txt
  tests/cores/storages/test_arangodb.py
Labels: A1

#1467 format react agent llama response to openai for openwebui display.
  comps/agent/src/agent.py
  comps/agent/src/integrations/strategy/base_agent.py
  comps/agent/src/integrations/strategy/react/planner.py
  comps/agent/src/integrations/strategy/react/utils.py
  comps/agent/src/integrations/tools.py
  comps/agent/src/requirements.txt
Labels: r1.3

#1107 Add tests + docs for BaseStatistics and generalize its code
  comps/cores/mega/base_statistics.py
  comps/cores/telemetry/README.md
  tests/cores/mega/test_base_statistics.py
Labels: A2

#1542 Misc apt and pip updates to Dockerfiles
  comps/dataprep/src/Dockerfile
  comps/finetuning/src/Dockerfile.xtune
  comps/image2image/src/Dockerfile
  comps/image2video/src/Dockerfile
  comps/llms/src/text-generation/Dockerfile.intel_hpu_phi4
  comps/rerankings/src/Dockerfile
  comps/retrievers/src/Dockerfile
  comps/text2graph/src/Dockerfile
  comps/third_parties/bridgetower/src/Dockerfile
  comps/third_parties/bridgetower/src/Dockerfile.intel_hpu
  comps/third_parties/gpt-sovits/src/Dockerfile
  comps/third_parties/ipex/src/Dockerfile
  comps/third_parties/llama-vision/src/Dockerfile
  comps/third_parties/llama-vision/src/Dockerfile.guard
  comps/third_parties/llama-vision/src/Dockerfile.tp
  comps/third_parties/llava/src/Dockerfile
  comps/third_parties/llava/src/Dockerfile.intel_hpu
  comps/third_parties/pathway/src/Dockerfile
  comps/third_parties/predictionguard/src/Dockerfile
  comps/third_parties/speecht5/src/Dockerfile
  comps/third_parties/speecht5/src/Dockerfile.intel_hpu
  comps/third_parties/video-llama/src/Dockerfile
  comps/third_parties/vllm/src/Dockerfile.intel_gpu
  comps/third_parties/wav2lip/src/Dockerfile
  comps/third_parties/wav2lip/src/Dockerfile.intel_hpu
  comps/third_parties/whisper/src/Dockerfile
  comps/third_parties/whisper/src/Dockerfile.intel_hpu
  comps/web_retrievers/src/Dockerfile
Labels: r1.3

#1551 Upgrade Torch and it's dependencies to v2.5.x for video-llama
  comps/third_parties/video-llama/src/Dockerfile
  comps/third_parties/video-llama/src/README.md
  comps/third_parties/video-llama/src/docker_compose_vllama.yaml
  comps/third_parties/video-llama/src/requirements.txt
  tests/lvms/test_lvms_video_llama.sh
Labels: WIP, r1.3

#1547 Remove Transformers versions from requirements.txt file
  comps/text2cypher/src/requirements.txt
Labels: bug, r1.3

#1525 new: `DataprepRequest` model
  comps/cores/proto/api_protocol.py
  comps/dataprep/src/integrations/elasticsearch.py
  comps/dataprep/src/integrations/milvus.py
  comps/dataprep/src/integrations/neo4j_langchain.py
  comps/dataprep/src/integrations/neo4j_llamaindex.py
  comps/dataprep/src/integrations/opensearch.py
  comps/dataprep/src/integrations/pgvect.py
  comps/dataprep/src/integrations/pipecone.py
  comps/dataprep/src/integrations/qdrant.py
  comps/dataprep/src/integrations/redis.py
  comps/dataprep/src/integrations/redis_finance.py
  comps/dataprep/src/integrations/vdms.py
  comps/dataprep/src/opea_dataprep_microservice.py
  tests/dataprep/dataprep_utils.sh
  tests/dataprep/test_dataprep_milvus.sh
  tests/dataprep/test_dataprep_redis.sh
Labels: feature, A0, r1.3, r1.4

#1558 Feature: `OpeaArangoDataprep` & `OpeaArangoRetriever`
  comps/cores/proto/api_protocol.py
  comps/dataprep/deployment/docker_compose/compose.yaml
  comps/dataprep/src/README_arangodb.md
  comps/dataprep/src/integrations/arangodb.py
  comps/dataprep/src/opea_dataprep_microservice.py
  comps/dataprep/src/requirements.txt
  comps/retrievers/deployment/docker_compose/compose.yaml
  comps/retrievers/src/README_arangodb.md
  comps/retrievers/src/integrations/arangodb.py
  comps/retrievers/src/integrations/config.py
  comps/retrievers/src/opea_retrievers_microservice.py
  comps/retrievers/src/requirements.txt
  comps/third_parties/arangodb/deployment/docker_compose/compose.yaml
  comps/third_parties/arangodb/src/README.md
  comps/third_parties/arangodb/src/__init__.py
  tests/dataprep/test_dataprep_arango.sh
  tests/retrievers/test_retrievers_arango.sh
Labels: feature, r1.3, r1.4

#1598 Update TGI docker image to 2.4.1
  comps/text2graph/src/README.md
  comps/text2sql/src/README.md
  comps/third_parties/tgi/deployment/docker_compose/compose.yaml
Labels: bug

#1583 dynamic model switching
  comps/cores/mega/micro_service.py
  comps/cores/mega/orchestrator.py
  tests/cores/mega/test_hybrid_service_orchestrator.py
Labels: A1, r1.3

#1610 Update base image version for opea/vllm-rocm image
  comps/third_parties/vllm/src/Dockerfile.amd_gpu
Labels: bug

#1620 fix pymilvus==2.5.6
  comps/dataprep/src/requirements.txt
  comps/retrievers/src/requirements.txt
Labels: bug, r1.3

#1621 fix vllm-openvino-arc openvino version issue
  comps/third_parties/vllm/deployment/docker_compose/compose.yaml
  comps/third_parties/vllm/src/Dockerfile.intel_gpu
Labels: bug, r1.3

#1631 Remove NV related package
  comps/third_parties/whisper/src/Dockerfile
Labels: bug, r1.3

#1629 Add sglang microservice for supporting llama4 model
  .github/workflows/docker/compose/third_parties-compose.yaml
  comps/llms/src/text-generation/README.md
  comps/third_parties/sglang/deployment/docker_compose/compose.yaml
  comps/third_parties/sglang/src/Dockerfile
  comps/third_parties/sglang/src/README.md
  comps/third_parties/sglang/src/__init__.py
  comps/third_parties/sglang/src/entrypoint.sh
  tests/third_parties/_test_third_parties_sglang.sh
Labels: feature, r1.4
