Repository opea-project/GenAIComps, pull requests merged in 2025-06, with the labels that each got.

#1762 Remove pytest cache while test cancelled
  .github/workflows/mix-megaservice-test.yml
Labels: WIP

#1511 Fix Orphaned Containers in Github Runners that Run Tests
  tests/rerankings/test_reranking_ovms.sh
Labels: Stale

#1678 FEAT: Enable MCP client tool for Agent
  comps/cores/mcp/README.md
  comps/cores/mcp/__init__.py
  comps/cores/mcp/client.py
  comps/cores/mcp/config.py
  comps/cores/mcp/manager.py
  comps/cores/mcp/tool.py
  tests/cores/mega/test_mcp_client.py
Labels: r1.4

#1395 Feature: OpenAI-compatible endpoint for text generation
  comps/cores/proto/api_protocol.py
  comps/llms/deployment/docker_compose/compose_text-generation.yaml
  comps/llms/src/text-generation/README_endpoint_openai.md
  comps/llms/src/text-generation/integrations/service.py
  tests/llms/test_llms_textgen_endpoint_openai.sh
Labels: A0

#1779 enable support for HNSW in dataprep and retriever for better performance
  comps/dataprep/src/integrations/redis.py
  comps/retrievers/src/integrations/config.py
  comps/retrievers/src/integrations/redis.py
  comps/retrievers/src/integrations/redis_schema_hnsw.yml
Labels: feature
